### ISSUE TITLE
Problem with class limits

### ISSUE THREAD

**Issue by JDMorris** [jcfaria/fdth#1]
Hi, I have a problem with class limits. 

library(fdth)
# generate some random values

data = runif(1000, min=900, max=1200)
# create class

dataClass = fdt(data, start=900, end=1200, h=25)
# class limits seems to be ok with plot

plot(dataClass)
# but class limit is not a multiple of 25 with summary

summary(dataClass,  col=c(1,2,4,5,6), format=TRUE, pattern="%.0f")

Jean-Daniel Morris

**Comment by jcfaria** [comment]
I think, it was fixed in the development version 1.2-0 (and it has new resources).

J.C.Faria
